### ISSUE TITLE
npm version is extremely outdated

### ISSUE THREAD

**Issue by ericLoansnap** [bitrise-steplib/steps-npm#5]
Currently looking at this, I am running npm version 6.0.1, but the latest available version is 0.9.1, which is quite deprecated.  Can you confirm this is correct?

**Comment by trapacska** [comment]
Hey @ericLoansnap !

You are right, however it is not related to this step itself. It depends on which version is preinstalled on the stack you use.

To have the latest npm, use this step with the command input: `install npm@latest -g`

Hope this helps.

So because this is independent of the step, I will mark this as an improvement to have an input field where you can select the npm version.

Thank you for reporting

**Comment by slotto** [comment]
Why is npm on such a outdated version. Would save a lot of build time if we don't need to upgrade on every build.

**Comment by lszucs** [comment]
Hi @ericLoansnap,

Good news! We have just released a new version of this step, where you can specify which npm version you wish to use to run your command! :)

You can find the release here:  https://github.com/bitrise-steplib/steps-npm/releases/tag/1.0.0

I'll close this issue, but if you need more info/help just let us know and we'll reopen it!
